services:
  lfm-api:
    image: vjdev/lfm-app:${TAG:-latest}
    build: .
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ${DATA_MOUNT_PATH:-lfm-data}:/app/data
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      - DB_PATH=/app/data/liquidity_monitor.db



volumes:
  lfm-data:
