services:
  lfm-api:
    image: vjdev/lfm-app:${TAG:-latest}
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app/data
      - ./src:/app/src
      - ./scripts:/app/scripts
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      - DB_PATH=/app/data/liquidity_monitor.db
      - REDIS_HOST=172.17.0.1


volumes:
  lfm-data:
